### ISSUE TITLE
run sample failed 

### ISSUE THREAD

**Issue by jonenet** [aws/aws-iot-device-sdk-java-v2#177]
Confirm by changing [ ] to [x] below:
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
window10

**Describe the question**
Exception in thread "main" java.lang.RuntimeException: Exception occurred during connect
	at shadow.ShadowSample.main(ShadowSample.java:250)
Caused by: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: The connection was closed unexpectedly.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at shadow.ShadowSample.main(ShadowSample.java:247)
Caused by: software.amazon.awssdk.crt.mqtt.MqttException: The connection was closed unexpectedly.
	at software.amazon.awssdk.crt.mqtt.MqttClientConnection.onConnectionComplete(MqttClientConnection.java:139)

**Comment by jmklix** [comment]
What is the policy attached for your IoT thing? Try using a fully permissive policy like this:
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```
And then limit it to only the actions/resources that you need once you get it working.
