### ISSUE TITLE
Basic PubSub sample does't work:software.amazon.awssdk.crt.mqtt.MqttException: socket is closed.

### ISSUE THREAD

**Issue by feihang12** [aws/aws-iot-device-sdk-java-v2#205]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution
the similar issue no finial solution found;
**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
i use Basic PubSub sample,add to my springboot project,config the root,cert,key,and endpoint,when run the project,it always show:

Exception in thread "main" java.lang.RuntimeException: Exception occurred during connect
	at com.han.pubsub.PubSub.Testmain(PubSub.java:337)
	at com.han.SpringbootRedistestApplication.main(SpringbootRedistestApplication.java:16)
Caused by: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: socket is closed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at com.han.pubsub.PubSub.Testmain(PubSub.java:334)
	... 1 more
Caused by: software.amazon.awssdk.crt.mqtt.MqttException: socket is closed.
	at software.amazon.awssdk.crt.mqtt.MqttClientConnection.onConnectionComplete(MqttClientConnection.java:139)

I don't know what happen,and i find the similar issue ,but no find answer,because the similar issue no finial solution found;
**SDK version number**
1.5.4
**Platform/OS/Hardware/Device**
What are you running the sdk on?
windows 10
**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**
i want the mqtt connect success and publish and sub topic success;

**Logs/output**
If applicable, add logs or error output.
Exception in thread "main" java.lang.RuntimeException: Exception occurred during connect
	at com.han.pubsub.PubSub.Testmain(PubSub.java:337)
	at com.han.SpringbootRedistestApplication.main(SpringbootRedistestApplication.java:16)
Caused by: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: socket is closed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at com.han.pubsub.PubSub.Testmain(PubSub.java:334)
	... 1 more
Caused by: software.amazon.awssdk.crt.mqtt.MqttException: socket is closed.
	at software.amazon.awssdk.crt.mqtt.MqttClientConnection.onConnectionComplete(MqttClientConnection.java:139)
To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
-Daws.crt.debugnative=true
-Daws.crt.log.destination=File
-Daws.crt.log.level=Trace
-Daws.crt.log.filename=<path and filename>
```

**Additional context**

**Comment by jmklix** [comment]
What is the iot policy that you are using to connect with?
You can try using the below policy for testing to rule out if the error is caused from a policy limitation.

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```
