### ISSUE TITLE
builder.withWill is not ok

### ISSUE THREAD

**Issue by ArvinSpace** [aws/aws-iot-device-sdk-java-v2#371]
### Describe the bug

Shadow example bug

if i add `builder.withWill` will exception when i run

> software.amazon.awssdk.iot.AwsIotMqttConnectionBuilder#withWill(software.amazon.awssdk.crt.mqtt.MqttMessage)

### Expected Behavior

Connected to clean session!
Subscribing to shadow delta events...
Subscribing to update responses...
Subscribing to get responses...
Requesting current shadow state...
Received initial shadow state
  Shadow reported value: off
color> 

### Current Behavior

Exception in thread "main" java.lang.RuntimeException: Exception occurred during connect
	at shadow.ShadowSample.main(ShadowSample.java:233)
Caused by: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: The connection was closed unexpectedly.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at shadow.ShadowSample.main(ShadowSample.java:230)
Caused by: software.amazon.awssdk.crt.mqtt.MqttException: The connection was closed unexpectedly.
	at software.amazon.awssdk.crt.mqtt.MqttClientConnection.onConnectionComplete(MqttClientConnection.java:140)

### Reproduction Steps

> 1. class method: utils.commandlineutils.CommandLineUtils#buildDirectMQTTConnection add the code below before 
 builder.build()
`
            MqttMessage message = new MqttMessage(topic, "{\"val\":\"yes\"}".getBytes(StandardCharsets.UTF_8), QualityOfService.AT_LEAST_ONCE);
            builder.withWill(message);
`

> 2. run sample https://github.com/aws/aws-iot-device-sdk-java-v2/blob/main/samples/Shadow/src/main/java/shadow/ShadowSample.java

### SDK version used

1.11.4

### Environment details (OS name and version, etc.)

Windows 10 Enterprise

**Comment by bretambrose** [comment]
I don't have any issues adding a will to the shadow sample's connection process.

My guess is that your will is destined for a topic that your IAM policy does not allow.  I believe IoT Core will reject connection attempts that include a will forbidden by your permission policy.

**Comment by bretambrose** [comment]
Closing absent further information

**Comment by ArvinSpace** [comment]
> I don't have any issues adding a will to the shadow sample's connection process.
> 
> My guess is that your will is destined for a topic that your IAM policy does not allow. I believe IoT Core will reject connection attempts that include a will forbidden by your permission policy.

yes, thx so much.
