### ISSUE TITLE
aws_tls_ctx_options_override_default_trust_store_from_path failed (aws_last_error: AWS_ERROR_INVALID_ARGUMENT(34)

### ISSUE THREAD

**Issue by houlovegu** [aws/aws-iot-device-sdk-java-v2#425]
### Describe the bug

I followed the official steps, but kept reporting this error, I tested nodejs,java version is always reporting this，I traced the code using the java version debug mode and found that the code threw an exception directly when creating the tlsContextOptionsNew object

### Expected Behavior

I hope you can help me solve this problem

### Current Behavior

when i run start.sh throw a error
```
start.sh ： node aws-iot-device-sdk-js-v2/samples/node/pub_sub/dist/index.js --endpoint a1hawfirpr4hfd-ats.iot.us-east-2.amazonaws.com --key test_ior.private.key --cert test_ior.cert.pem --ca_file root-CA.crt --client_id sdk-nodejs-v2 --topic sdk/test/js
Error: aws-c-common: AWS_ERROR_INVALID_ARGUMENT, An invalid argument was passed to a function.
    at new TlsContext (E:\connect_device_package\aws-iot-device-sdk-js-v2\node_modules\aws-crt\dist\native\io.js:321:33)
    at new ClientTlsContext (E:\connect_device_package\aws-iot-device-sdk-js-v2\node_modules\aws-crt\dist\native\io.js:339:9)
    at AwsIotMqttConnectionConfigBuilder.build (E:\connect_device_package\aws-iot-device-sdk-js-v2\node_modules\aws-crt\dist\native\aws_iot.js:435:35)
    at build_direct_mqtt_connection_from_args (E:\connect_device_package\aws-iot-device-sdk-js-v2\samples\util\cli_args.js:366:35)
    at Object.build_connection_from_cli_args (E:\connect_device_package\aws-iot-device-sdk-js-v2\samples\util\cli_args.js:382:16)
    at Object.<anonymous> (E:\connect_device_package\aws-iot-device-sdk-js-v2\samples\node\pub_sub\dist\index.js:87:40)
    at Generator.next (<anonymous>)
    at E:\connect_device_package\aws-iot-device-sdk-js-v2\samples\node\pub_sub\dist\index.js:16:71
    at new Promise (<anonymous>)
    at __awaiter (E:\connect_device_package\aws-iot-device-sdk-js-v2\samples\node\pub_sub\dist\index.js:12:12) {
  code: 'An invalid argument was passed to a function.'
}
```

### Reproduction Steps

Open AWS IOT and click the connection tutorial, follow the steps to connect to the device will provide sdk, then run the script error

### SDK version used

aws-iot-device-sdk-js-v2

### Environment details (OS name and version, etc.)

windows10,nodejs 18+,npm 6+

**Comment by yasminetalby** [comment]
Hello @houlovegu ,

Thank you very much for your submission.

I am not able to reproduce this issue. Following the[ IoT Core connect device tutorial](https://docs.aws.amazon.com/iot/latest/developerguide/iot-quick-start.html) leads to successful outcome for me. 

Have you made any modification to the provided root-CA/certificate/key?
Have you made any modification to the start.sh file?
Have you followed this tutorial for an existing thing or attempted to create a new thing?

Thank you very much for your time and collaboration.

Sincerely,

Yasmine
