### ISSUE TITLE
"TLS (SSL) negotiation failed" When trying to connect MqttClientConnection

### ISSUE THREAD

**Issue by JeYdevoir** [aws/aws-iot-device-sdk-java-v2#56]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Mac High Sierra

**Describe the question**
I'm trying to follow the basic pub-sub example to try and get a handle for this SDK, but I'm getting a connection issue. I've done some searching in various areas including previous issues of this github page but nothing has worked for me so far. I'll provide the specifics below.

I'm getting the follow exception:
```
Caused by: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: TLS (SSL) negotiation failed
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:359)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1921)
        at com.tracelink.core.service.MessagingService.connectWithNewStuff(MessagingService.java:512)
        at com.tracelink.core.service.MessagingService.connectToMqtt(MessagingService.java:483) 
        at com.tracelink.core.service.MessagingService.establishConnection(MessagingService.java:458) 
        at com.tracelink.core.service.MessagingService.connect(MessagingService.java:371) 
        at com.tracelink.core.service.-$$Lambda$QGvInWxgQaux-XIMYYPhle8KTFw.run(Unknown Source:2) 
        at com.tracelink.core.service.MessagingService.lambda$wrap$0(MessagingService.java:391) 
        at com.tracelink.core.service.-$$Lambda$MessagingService$knrcCIKmsULdFEyFPCA7CjogF58.call(Unknown Source:2) 
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44) 
        at io.reactivex.Single.subscribe(Single.java:3096) 
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: software.amazon.awssdk.crt.mqtt.MqttException: TLS (SSL) negotiation failed
        at software.amazon.awssdk.crt.mqtt.MqttClientConnection.onConnectionComplete(MqttClientConnection.java:145)
```

When I try to run "boolean sessionPresent = connected.get();" in this snippit:
```
private void connectWithNewStuff() throws Exception {
        LOG.debug("/*-+-*/ New connection start!");
        MqttMessage lwt = new MqttMessage(getString(R.string.messaging_service_lwt_topic),
                getString(R.string.messaging_service_aws_lwt).getBytes());
        String endpoint = SharedPreferenceHelper.getAwsConnectionURL(this);
        LOG.debug("/*-+-*/ Endpoint url: " + endpoint);

        try (EventLoopGroup eventLoopGroup = new EventLoopGroup(1);
             HostResolver resolver = new HostResolver(eventLoopGroup);
             ClientBootstrap bootstrap = new ClientBootstrap(eventLoopGroup, resolver);
             AwsIotMqttConnectionBuilder builder = AwsIotMqttConnectionBuilder
                     .newMtlsBuilder(getCertificate(), getPrivateKey())
                     .withPort((short) 8883)
                     .withBootstrap(bootstrap)
                     .withWill(lwt, QualityOfService.AT_MOST_ONCE, false)
                     .withClientId("02:00:00:44:55:46")
                     .withCertificateAuthority(getRootCa())
                     .withEndpoint(endpoint)) {
            LOG.debug("/*-+-*/ Builder Established");
            try (MqttClientConnection connection = builder.build()) {
                LOG.debug("/*-+-*/ Connection built~");
                CompletableFuture<Boolean> connected = connection.connect();
                try {
                    boolean sessionPresent = connected.get();
                    LOG.debug("/*-+-*/ Connected to " + (!sessionPresent ? "new" : "existing")
                            + " session!");
                } catch (Exception ex) {
                    throw new RuntimeException(
                            "/*-+-*/ Exception occurred during new connect stuff", ex);
                }
        }
}
```

**Comment by JeYdevoir** [comment]
Just to make sure I wasn't doing anything obvious, I tried running the PubSub.java in Samples on its own and got the same exact exception. These were my program arguments:
```
-c /Users/jlamendola/Documents/Certs/46cert.txt
-k /Users/jlamendola/Documents/Certs/46key.txt
-e [obfuscated URL]
-m "Helllooo _WORLD!_"
--clientId 02:00:00:44:55:46
```

**Comment by JonathanHenson** [comment]
Are you per chance not using the ats endpoint?

**Comment by JeYdevoir** [comment]
What's the difference? I'm using "[letters and numbers].iot.us-east-1.amazonaws.com"

**Comment by JonathanHenson** [comment]
The CA for the non-ats endpoints has been pulled.
https://aws.amazon.com/about-aws/whats-new/2018/08/aws-iot-core-adds-new-endpoints-serving-amazon-trust-services-signed-certificates-to-help-customers-avoid-symantec-distrust-issues/

**Comment by JeYdevoir** [comment]
After doing a little research, seems I just needed to add a "-ats" to the letters and numbers and now it seems to be working. Didn't realize that was a thing, thank you for your help.
