### ISSUE TITLE
Problem UnsatisfiedLinkError AWS CRT lib in Windows development environment. 

### ISSUE THREAD

**Issue by lkolodziejek** [aws/aws-iot-device-sdk-java-v2#61]
I've searched for previous similar issues and didn't find any solution

**Platform/OS/Hardware/Device**

OS : Windows 10
JAVA : jdk1.8.0_121
aws-iot-device-sdk v1.0.6

**Describe the question**

I get following Error when IoT class is trying to initiate CRT:

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\lukas\AppData\Local\Temp\AWSCRT_15918817021667267130506483563287aws-crt-jni.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at software.amazon.awssdk.crt.CRT.loadLibraryFromJar(CRT.java:154)
	at software.amazon.awssdk.crt.CRT.<clinit>(CRT.java:38)
	at software.amazon.awssdk.crt.CrtResource.<clinit>(CrtResource.java:99)
	at IOTDevice.main(IOTDevice.java:50)

The file (AWSCRT_15918817021667267130506483563287aws-crt-jni.dll) is available under indicated location, I'm not sure what dependent libraries might be missing. 

Thank you in advance,
Lukasz

**Comment by justinboswell** [comment]
We have a new release of the IoT Device SDK coming out later today which will upgrade the dependency on the CRT to latest (https://github.com/awslabs/aws-crt-java/releases/tag/v0.5.9). Otherwise, just pull the latest CRT locally for the time being, there was an issue with the windows DLLs depending on debug MSVCRT for the last release.
